global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'kafka'
    scrape_interval: 10s
    static_configs:
    - targets: ['127.0.0.1:9170','127.0.0.1:9270','127.0.0.1:9370']
  - job_name: 'kafka_topics'
    scrape_interval: 10s
    static_configs:
    - targets: ['127.0.0.1:9191']
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9090']