---
version: '2'
services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:5.0.1
    restart: on-failure:3
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
      JMX_PORT: 2171
    volumes:
      - ${PROMETHEUS_DIR}:/etc/prometheus
    network_mode: host

  zookeeper2:
    image: confluentinc/cp-zookeeper:5.0.1
    restart: on-failure:3
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
      JMX_PORT: 2271
    volumes:
      - ${PROMETHEUS_DIR}:/etc/prometheus
    network_mode: host

  zookeeper3:
    image: confluentinc/cp-zookeeper:5.0.1
    restart: on-failure:3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
      JMX_PORT: 2371
    volumes:
      - ${PROMETHEUS_DIR}:/etc/prometheus
    network_mode: host

  kafka-1:
    image: confluentinc/cp-kafka:5.0.1
    network_mode: host
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19094
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      JMX_PORT: 9171
      KAFKA_OPTS: -javaagent:/etc/prometheus/jmx_prometheus_javaagent-0.3.1.jar=9170:/etc/prometheus/kafka.yml
    volumes:
      - ${PROMETHEUS_DIR}:/etc/prometheus

  kafka-2:
    image: confluentinc/cp-kafka:5.0.1
    network_mode: host
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29094
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      JMX_PORT: 9271
      KAFKA_OPTS: -javaagent:/etc/prometheus/jmx_prometheus_javaagent-0.3.1.jar=9270:/etc/prometheus/kafka.yml
    volumes:
      - ${PROMETHEUS_DIR}:/etc/prometheus

  kafka-3:
    image: confluentinc/cp-kafka:5.0.1
    network_mode: host
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39094
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      JMX_PORT: 9371
      KAFKA_OPTS: -javaagent:/etc/prometheus/jmx_prometheus_javaagent-0.3.1.jar=9370:/etc/prometheus/kafka.yml
    volumes:
      - ${PROMETHEUS_DIR}:/etc/prometheus

  grafana:
    image: grafana/grafana
    network_mode: host
  
  prometheus:
    image: prom/prometheus
    network_mode: host
    volumes:
      - ${PROMETHEUS_DIR}:/etc/prometheus