---
version: '2'
services:
  zookeeper-sasl-1:
    image: confluentinc/cp-zookeeper:5.0.1
    # This is required because Zookeeper can fail if kerberos is still initializing.
    restart: on-failure:3
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: quickstart.confluent.io:22888:23888;quickstart.confluent.io:32888:33888;quickstart.confluent.io:42888:43888
      JMX_PORT: 2171
      KAFKA_OPTS: -javaagent:/etc/prometheus/jmx_prometheus_javaagent-0.3.1.jar=2170:/etc/prometheus/zookeeper.yml -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_1_jaas.conf
        -Djava.security.krb5.conf=/etc/kafka/secrets/krb.conf
        -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        -Dsun.security.krb5.debug=true
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
      - ${KAFKA_SASL_PROMETHEUS_DIR}:/etc/prometheus
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"
      - "quickstart.confluent.io:10.3.141.213"

  zookeeper-sasl-2:
    image: confluentinc/cp-zookeeper:5.0.1
    # This is required because Zookeeper can fail if kerberos is still initializing.
    restart: on-failure:3
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: quickstart.confluent.io:22888:23888;quickstart.confluent.io:32888:33888;quickstart.confluent.io:42888:43888
      JMX_PORT: 2271
      KAFKA_OPTS: -javaagent:/etc/prometheus/jmx_prometheus_javaagent-0.3.1.jar=2270:/etc/prometheus/zookeeper.yml -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_2_jaas.conf
        -Djava.security.krb5.conf=/etc/kafka/secrets/krb.conf
        -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        -Dsun.security.krb5.debug=true
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
      - ${KAFKA_SASL_PROMETHEUS_DIR}:/etc/prometheus
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"
      - "quickstart.confluent.io:10.3.141.213"


  zookeeper-sasl-3:
    image: confluentinc/cp-zookeeper:5.0.1
    # This is required because Zookeeper can fail if kerberos is still initializing.
    restart: on-failure:3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: quickstart.confluent.io:22888:23888;quickstart.confluent.io:32888:33888;quickstart.confluent.io:42888:43888
      JMX_PORT: 2371
      KAFKA_OPTS: -javaagent:/etc/prometheus/jmx_prometheus_javaagent-0.3.1.jar=2370:/etc/prometheus/zookeeper.yml -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_3_jaas.conf
        -Djava.security.krb5.conf=/etc/kafka/secrets/krb.conf
        -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        -Dsun.security.krb5.debug=true
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
      - ${KAFKA_SASL_PROMETHEUS_DIR}:/etc/prometheus
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"
      - "quickstart.confluent.io:10.3.141.213"

  kerberos:
    image: confluentinc/cp-kerberos:5.0.1
    network_mode: host
    hostname: quickstart.confluent.io
    environment:
      BOOTSTRAP: 0
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/tmp/keytab
      - /dev/urandom:/dev/random
    extra_hosts:
      - "moby:127.0.0.1"
      - "quickstart.confluent.io:10.3.141.213"

  kafka-sasl-1:
    image: confluentinc/cp-kafka:5.0.1
    network_mode: host
    # This is required because Kafka can fail if kerberos is still initializing.
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: quickstart.confluent.io:22181,quickstart.confluent.io:32181,quickstart.confluent.io:42181
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://quickstart.confluent.io:19094
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: GSSAPI
      KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
      KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG
      JMX_PORT: 9171
      KAFKA_OPTS: -javaagent:/etc/prometheus/jmx_prometheus_javaagent-0.3.1.jar=9170:/etc/prometheus/kafka.yml -Djava.security.auth.login.config=/etc/kafka/secrets/broker1_jaas.conf
        -Djava.security.krb5.conf=/etc/kafka/secrets/krb.conf
        -Dsun.security.krb5.debug=true
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
      - ${KAFKA_SASL_PROMETHEUS_DIR}:/etc/prometheus
    extra_hosts:
      - "moby:127.0.0.1"
      - "quickstart.confluent.io:10.3.141.213"

  kafka-sasl-2:
    image: confluentinc/cp-kafka:5.0.1
    network_mode: host
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: quickstart.confluent.io:22181,quickstart.confluent.io:32181,quickstart.confluent.io:42181
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://quickstart.confluent.io:29094
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: GSSAPI
      KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
      KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG
      JMX_PORT: 9271
      KAFKA_OPTS: -javaagent:/etc/prometheus/jmx_prometheus_javaagent-0.3.1.jar=9270:/etc/prometheus/kafka.yml -Djava.security.auth.login.config=/etc/kafka/secrets/broker2_jaas.conf
        -Djava.security.krb5.conf=/etc/kafka/secrets/krb.conf
        -Dsun.security.krb5.debug=true
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
      - ${KAFKA_SASL_PROMETHEUS_DIR}:/etc/prometheus
    extra_hosts:
      - "moby:127.0.0.1"
      - "quickstart.confluent.io:10.3.141.213"

  kafka-sasl-3:
    image: confluentinc/cp-kafka:5.0.1
    network_mode: host
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: quickstart.confluent.io:22181,quickstart.confluent.io:32181,quickstart.confluent.io:42181
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://quickstart.confluent.io:39094
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: GSSAPI
      KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
      KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG
      JMX_PORT: 9371
      KAFKA_OPTS: -javaagent:/etc/prometheus/jmx_prometheus_javaagent-0.3.1.jar=9370:/etc/prometheus/kafka.yml -Djava.security.auth.login.config=/etc/kafka/secrets/broker3_jaas.conf
        -Djava.security.krb5.conf=/etc/kafka/secrets/krb.conf
        -Dsun.security.krb5.debug=true
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
      - ${KAFKA_SASL_PROMETHEUS_DIR}:/etc/prometheus
    extra_hosts:
      - "moby:127.0.0.1"
      - "quickstart.confluent.io:10.3.141.213"

  prometheus:
    image: prom/prometheus
    network_mode: host
    volumes:
      - ${KAFKA_SASL_PROMETHEUS_DIR}:/etc/prometheus

  grafana:
    image: grafana/grafana
    network_mode: host