{
 "title": "Kafka Network",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Processing Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RequestQueueSize",
   "type": "graph",
   "description": "Size of the request queue. A congested request queue will not be able to process incoming or outgoing requests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestchannel_requestqueuesize",
     "legendFormat": "{{instance}}-{{job}}"
    }
   ]
  },
  {
   "title": "RequestQueueTimeMs Produce",
   "type": "graph",
   "description": "Time the request waits in the request queue",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requestqueuetimems{request=~\"Produce|OffsetCommit\"}[$__range])",
     "legendFormat": "{{instance}}-{{job}}-{{request}}"
    }
   ]
  },
  {
   "title": "TotalTimeMS Produce",
   "type": "graph",
   "description": "Total time in ms to serve the produce request",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_totaltimems{request=~\"Produce|OffsetCommit\"}[$__range])",
     "legendFormat": "{{instance}}-{{job}}-{{request}}"
    }
   ]
  },
  {
   "title": "RequestsPerSec",
   "type": "graph",
   "description": "Request rate.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total[$__range])",
     "legendFormat": "{{instance}}-{{job}}-{{request}}"
    }
   ]
  }
 ]
}