{
 "title": "Kafka Server",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UnderReplicatedPartitions",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |). Alert if value is greater than 0.",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions)"
    }
   ]
  },
  {
   "title": "ActiveControllerCount",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster. Alert if the aggregated sum across all brokers in the cluster is anything other than 1 because there should be exactly one controller per cluster.",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "OfflinePartitionsCount",
   "type": "singlestat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable. Alert if value is greater than 0.",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount)"
    }
   ]
  },
  {
   "title": "RequestHandlerAvgIdlePercent",
   "type": "graph",
   "description": "Average fraction of time the request handler threads are idle. Values are between 0 (all resources are used) and 1 (all resources are available)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent[$__range])/10000000",
     "legendFormat": "{{instance}}-{{job}}"
    }
   ]
  },
  {
   "title": "Produce PurgatorySize",
   "type": "graph",
   "description": "Number of requests waiting in the producer purgatory. This should be non-zero when acks=all is used on the producer.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_produce",
     "legendFormat": "{{instance}}-{{job}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "TotalProduceRequestsPerSec",
   "type": "graph",
   "description": "Produce request rate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_totalproducerequests_total[$__range])",
     "legendFormat": "{{instance}}-{{job}}-{{topic}}"
    }
   ]
  },
  {
   "title": "FailedProduceRequestsPerSec",
   "type": "graph",
   "description": "Produce request rate for requests that failed.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_failedproducerequests_total[$__range])",
     "legendFormat": "{{instance}}-{{job}}-{{topic}}"
    }
   ]
  },
  {
   "title": "TotalFetchRequestsPerSec",
   "type": "graph",
   "description": "Fetch request rate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_totalfetchrequests_total[$__range])",
     "legendFormat": "{{instance}}-{{job}}-{{topic}}"
    }
   ]
  },
  {
   "title": "FailedFetchRequestsPerSec",
   "type": "graph",
   "description": "Fetch request rate for requests that failed.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_failedfetchrequests_total[$__range])",
     "legendFormat": "{{instance}}-{{job}}-{{topic}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "MessagesInPerSec",
   "type": "graph",
   "description": "Aggregate incoming message rate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total[$__range])",
     "legendFormat": "{{instance}}-{{job}}-{{topic}}"
    }
   ]
  },
  {
   "title": "BytesInPerSec",
   "type": "graph",
   "description": "Aggregate incoming byte rate.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total[$__range])",
     "legendFormat": "{{instance}}-{{job}}-{{topic}}"
    }
   ]
  },
  {
   "title": "BytesOutPerSec",
   "type": "graph",
   "description": "Aggregate outgoing byte rate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\"}[$__range])"
    }
   ]
  },
  { "title": "Leader Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "LeaderCount",
   "type": "graph",
   "description": "Number of leaders on this broker. This should be mostly even across all brokers. If not, set auto.leader.rebalance.enable to true on all brokers in the cluster.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount",
     "legendFormat": "{{instance}}-{{job}}"
    }
   ]
  },
  {
   "title": "PartitionCount",
   "type": "graph",
   "description": "Number of partitions on this broker. This should be mostly even across all brokers.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_partitioncount",
     "legendFormat": "{{instance}}-{{job}}"
    }
   ]
  },
  {
   "title": "FetcherLagMetrics",
   "type": "graph",
   "description": "Lag in number of messages per follower replica. This is useful to know if the replica is slow or has stopped replicating from the leader.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_fetcherlagmetrics_consumerlag",
     "legendFormat": "{{instance}}-{{job}}-{{clientId}}-{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Clean/Unclean LeaderElectionRate",
   "type": "graph",
   "description": "Leader election rate",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_controller_controllerstats_leaderelectionrateandtimems[$__range])",
     "legendFormat": "{{instance}}-{{job}}-clean"
    },
    {
     "expr": "rate(kafka_controller_controllerstats_uncleanleaderelectionspersec[$__range])",
     "legendFormat": "{{instance}}-{{job}}-unclean"
    }
   ]
  },
  {
   "title": "Replica MaxLag",
   "type": "graph",
   "description": "Maximum lag in messages between the follower and leader replicas. This is controlled by the replica.lag.max.messages config.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicafetchermanager_maxlag",
     "legendFormat": "{{instance}}-{{job}}"
    }
   ]
  }
 ]
}