{
 "title": "Kafka Server",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UnderReplicatedPartitions",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |). Alert if value is greater than 0.",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions)",
     "measurement": "kafka_replica_manager",
     "select": [
      [
       {
        "params": [
         "UnderReplicatedPartitions.Value"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ActiveControllerCount",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster. Alert if the aggregated sum across all brokers in the cluster is anything other than 1 because there should be exactly one controller per cluster.",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "kafka_controller",
     "query": "select sum(\"last\") from (SELECT last(\"ActiveControllerCount.Value\") FROM \"kafka_controller\" WHERE $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "ActiveControllerCount.Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OfflinePartitionsCount",
   "type": "singlestat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable. Alert if value is greater than 0.",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount)",
     "measurement": "kafka_controller",
     "select": [
      [
       { "params": [ "OfflinePartitionsCount.Value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RequestHandlerAvgIdlePercent",
   "type": "graph",
   "description": "Average fraction of time the request handler threads are idle. Values are between 0 (all resources are used) and 1 (all resources are available)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent[$__range])/10000000",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}-{{job}}",
     "measurement": "kafka_requesthandleravgidlepercent",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Produce PurgatorySize",
   "type": "graph",
   "description": "Number of requests waiting in the producer purgatory. This should be non-zero when acks=all is used on the producer.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_produce",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}-{{job}}",
     "measurement": "kafka_purgatory",
     "select": [
      [
       { "params": [ "Produce.NumDelayedOperations" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "TotalProduceRequestsPerSec",
   "type": "graph",
   "description": "Produce request rate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(kafka_server_brokertopicmetrics_totalproducerequests_total[$__range])",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}-{{job}}-{{topic}}",
     "measurement": "kafka_topics",
     "select": [
      [
       {
        "params": [
         "TotalProduceRequestsPerSec.Count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FailedProduceRequestsPerSec",
   "type": "graph",
   "description": "Produce request rate for requests that failed.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(kafka_server_brokertopicmetrics_failedproducerequests_total[$__range])",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}-{{job}}-{{topic}}",
     "measurement": "kafka_topics",
     "select": [
      [
       {
        "params": [
         "FailedProduceRequestsPerSec.Count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "TotalFetchRequestsPerSec",
   "type": "graph",
   "description": "Fetch request rate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(kafka_server_brokertopicmetrics_totalfetchrequests_total[$__range])",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}-{{job}}-{{topic}}",
     "measurement": "kafka_topics",
     "select": [
      [
       { "params": [ "TotalFetchRequestsPerSec.Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FailedFetchRequestsPerSec",
   "type": "graph",
   "description": "Fetch request rate for requests that failed.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(kafka_server_brokertopicmetrics_failedfetchrequests_total[$__range])",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}-{{job}}-{{topic}}",
     "measurement": "kafka_topics",
     "select": [
      [
       {
        "params": [
         "FailedFetchRequestsPerSec.Count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "MessagesInPerSec",
   "type": "graph",
   "description": "Aggregate incoming message rate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total[$__range])",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}-{{job}}-{{topic}}",
     "measurement": "kafka_topics",
     "select": [
      [
       { "params": [ "MessagesInPerSec.Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "$tag_host-$tag_topic",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kafka_topic",
     "select": [
      [
       { "params": [ "MessagesInPerSec.Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "BytesInPerSec",
   "type": "graph",
   "description": "Aggregate incoming byte rate.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total[$__range])",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}-{{job}}-{{topic}}",
     "measurement": "kafka_topics",
     "select": [
      [
       { "params": [ "BytesInPerSec.Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "BytesOutPerSec",
   "type": "graph",
   "description": "Aggregate outgoing byte rate.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\"}[$__range])",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kafka_topics",
     "select": [
      [
       { "params": [ "BytesOutPerSec.Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  { "title": "Leader Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "LeaderCount",
   "type": "graph",
   "description": "Number of leaders on this broker. This should be mostly even across all brokers. If not, set auto.leader.rebalance.enable to true on all brokers in the cluster.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "kafka_server_replicamanager_leadercount",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}-{{job}}",
     "measurement": "kafka_replica_manager",
     "select": [
      [
       { "params": [ "LeaderCount.Value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PartitionCount",
   "type": "graph",
   "description": "Number of partitions on this broker. This should be mostly even across all brokers.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "kafka_server_replicamanager_partitioncount",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}-{{job}}",
     "measurement": "kafka_replica_manager",
     "select": [
      [
       { "params": [ "PartitionCount.Value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FetcherLagMetrics",
   "type": "graph",
   "description": "Lag in number of messages per follower replica. This is useful to know if the replica is slow or has stopped replicating from the leader.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host-$tag_topic-$tag_partition-$tag_clientId",
     "expr": "kafka_server_fetcherlagmetrics_consumerlag",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "clientId" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}-{{job}}-{{clientId}}-{{topic}}-{{partition}}",
     "measurement": "kafka_fetcherlagmetrics",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clean/Unclean LeaderElectionRate",
   "type": "graph",
   "description": "Leader election rate",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host-Clean",
     "expr": "rate(kafka_controller_controllerstats_leaderelectionrateandtimems[$__range])",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}-{{job}}-clean",
     "measurement": "kafka_controller",
     "select": [
      [
       {
        "params": [
         "LeaderElectionRateAndTimeMs.Count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "$tag_host-Unclean",
     "expr": "rate(kafka_controller_controllerstats_uncleanleaderelectionspersec[$__range])",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}-{{job}}-unclean",
     "measurement": "kafka_controller",
     "select": [
      [
       {
        "params": [
         "UncleanLeaderElectionsPerSec.Count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replica MaxLag",
   "type": "graph",
   "description": "Maximum lag in messages between the follower and leader replicas. This is controlled by the replica.lag.max.messages config.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "kafka_server_replicafetchermanager_maxlag",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}-{{job}}",
     "measurement": "kafka_replicafetchermanager",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}